import { Inject,Injectable } from '@nestjs/common';
import { z } from 'zod';
import { Db,hash } from '../common/db';
import { parse,uuid,money,fail,pageQuery,paged } from '../common/errors';
import { publicProfile } from '../sanatoriums/sanatorium.service';
import type { Actor } from '../auth/permissions';

@Injectable()
export class CatalogService{
  constructor(@Inject(Db) readonly db:Db){}
  private async where(){const eligible=await this.db.subscription.findMany({where:{status:{in:['ACTIVE','TRIAL','PAST_DUE']},graceEndsAt:{gt:new Date()}},select:{sanatoriumId:true}});return {status:'ACTIVE',publicRevisionId:{not:null},OR:[{subscriptionRequired:false},{id:{in:eligible.map(s=>s.sanatoriumId)}}]};}
  async list(query:unknown){const i=parse(pageQuery.extend({q:z.string().trim().max(100).optional(),region:z.string().max(80).optional(),amenity:z.string().max(80).optional(),max_price:money.optional(),sort:z.enum(['NAME','PRICE']).default('NAME')}).strict(),query);const all=await this.db.sanatorium.findMany({where:await this.where()});const revisions=await this.db.sanatoriumRevision.findMany({where:{id:{in:all.map(s=>s.publicRevisionId!)}}});const rates=await this.db.ratePlan.findMany({where:{sanatoriumId:{in:all.map(s=>s.id)},active:true},select:{sanatoriumId:true,baseAmount:true}});const ratings=await this.db.review.groupBy({by:['sanatoriumId'],where:{status:'PUBLISHED',sanatoriumId:{in:all.map(s=>s.id)}},_avg:{rating:true},_count:{id:true}});
    let rows=all.map(s=>{const r=revisions.find(r=>r.id===s.publicRevisionId)!;const data=publicProfile(r.data);const prices=rates.filter(r=>r.sanatoriumId===s.id).map(r=>r.baseAmount);const amount=prices.length?prices.reduce((a,b)=>a<b?a:b):null;const rating=ratings.find(r=>r.sanatoriumId===s.id);return {id:s.id,...data,from_amount:amount?.toString()??null,price_label:'Boshlang‘ich tarif; yakuniy narx bron hisobida',online_booking_available:s.paymentReady&&prices.length>0,rating:rating?{average:rating._avg.rating,count:rating._count.id}:null};});
    if(i.q){const q=i.q.toLocaleLowerCase();rows=rows.filter(r=>`${r.name} ${r.description} ${r.region}`.toLocaleLowerCase().includes(q));}if(i.region)rows=rows.filter(r=>r.region===i.region);if(i.amenity)rows=rows.filter(r=>r.amenities?.includes(i.amenity));if(i.max_price)rows=rows.filter(r=>r.from_amount!==null&&BigInt(r.from_amount)<=BigInt(i.max_price!));rows.sort((a,b)=>i.sort==='PRICE'?(BigInt(a.from_amount??'9000000000000000000')<BigInt(b.from_amount??'9000000000000000000')?-1:1):String(a.name).localeCompare(String(b.name)));return paged(rows.slice((i.page-1)*i.limit,i.page*i.limit),rows.length,i.page,i.limit);
  }
  async get(id:string){parse(uuid,id);const s=await this.db.sanatorium.findFirst({where:{...await this.where(),id}});if(!s)fail('NOT_FOUND','Sanatoriya topilmadi',404);const revision=await this.db.sanatoriumRevision.findUniqueOrThrow({where:{id:s.publicRevisionId!}});const [room_types,rawRates,reviews]=await Promise.all([this.db.roomType.findMany({where:{sanatoriumId:id,active:true}}),this.db.ratePlan.findMany({where:{sanatoriumId:id,active:true}}),this.db.review.findMany({where:{sanatoriumId:id,status:'PUBLISHED'},select:{id:true,rating:true,text:true,reply:true,createdAt:true},take:50,orderBy:{createdAt:'desc'}})]);const policies=await this.db.refundPolicy.findMany({where:{id:{in:rawRates.map(r=>r.policyId)}}});return {id:s.id,...publicProfile(revision.data),room_types,rate_plans:rawRates.map(r=>({...r,policy:policies.find(p=>p.id===r.policyId)})),reviews:reviews.map(r=>({...r,verified_stay:true})),online_booking_available:s.paymentReady&&rawRates.length>0};}
  async favorites(actor:Actor){const saved=await this.db.favorite.findMany({where:{userId:actor.id}});const all=await this.list({limit:100});return all.data.filter((r:any)=>saved.some(f=>f.sanatoriumId===r.id));}
  async favorite(actor:Actor,id:string,body:unknown){parse(uuid,id);const i=parse(z.object({saved:z.boolean()}).strict(),body);if(i.saved){await this.get(id);await this.db.favorite.upsert({where:{userId_sanatoriumId:{userId:actor.id,sanatoriumId:id}},create:{userId:actor.id,sanatoriumId:id},update:{}});}else await this.db.favorite.deleteMany({where:{userId:actor.id,sanatoriumId:id}});return {saved:i.saved};}
  async ads(){const candidates=await this.db.adCampaign.findMany({where:{status:'APPROVED',startsAt:{lte:new Date()},endsAt:{gt:new Date()},invoiceId:{not:null}}});const rows=[];for(const ad of candidates){const invoice=await this.db.invoice.findUnique({where:{id:ad.invoiceId!}});if(invoice?.status!=='PAID'||!await this.db.sanatorium.findFirst({where:{...await this.where(),id:ad.sanatoriumId}}))continue;rows.push({id:ad.id,sanatorium_id:ad.sanatoriumId,title:ad.title,placement:ad.placement,...ad.data as object,sponsored:true,label:'Reklama'});}return rows;}
  async adEvent(id:string,body:unknown,ip:string){parse(uuid,id);const i=parse(z.object({kind:z.enum(['IMPRESSION','CLICK'])}).strict(),body);if(!(await this.ads()).some(a=>a.id===id))fail('NOT_FOUND','Reklama mavjud emas',404);const key=hash(`${id}:${i.kind}:${ip}:${Math.floor(Date.now()/900000)}`);await this.db.adEvent.upsert({where:{dedupeKey:key},create:{campaignId:id,kind:i.kind,dedupeKey:key},update:{}});return {success:true};}
  async entries(){return this.db.catalogEntry.findMany({orderBy:[{kind:'asc'},{name:'asc'}]});}
}
