import { Inject,Injectable } from '@nestjs/common';
import { z } from 'zod';
import { Db,audit,emit,type Tx } from '../common/db';
import { parse,uuid,positiveMoney,reason,fail,pageQuery,paged } from '../common/errors';
import { Actor,scope,requirePlatform,tenantIds } from '../auth/permissions';
import { financialLock,refundReserve } from '../payments/payment.service';
import { bookingBalance,post } from '../ledger/ledger';

@Injectable()
export class FinanceService{
  constructor(@Inject(Db) readonly db:Db){}
  private async booking(tx:Tx,actor:Actor,id:string,permission='refunds.request'){
    const b=await tx.booking.findUnique({where:{id}});if(!b)fail('NOT_FOUND','Bron topilmadi',404);if(actor.kind==='CUSTOMER'){if(b.userId!==actor.id)fail('NOT_FOUND','Bron topilmadi',404);}else scope(actor,b.sanatoriumId,permission);await financialLock(tx,b.sanatoriumId);return tx.booking.findUniqueOrThrow({where:{id}});
  }
  async refundRequest(actor:Actor,id:string,body:unknown,key?:string){parse(uuid,id);const i=parse(z.object({reason,force:z.boolean().default(false)}).strict(),body);if(i.force)requirePlatform(actor,'refunds.approve');
    return this.db.idempotent(actor.id,'refund.request',key,{booking_id:id,...i},async tx=>{const b=await this.booking(tx,actor,id);const order=await tx.paymentOrder.findUnique({where:{bookingId:id}});if(!order||order.status!=='SUCCEEDED')fail('REFUND_UNAVAILABLE','Tasdiqlangan onlayn to‘lov yo‘q');
      if(!i.force&&b.status!=='PAYMENT_EXCEPTION'){const policies=(b.snapshot as any).policies;const deadline=Date.parse(`${b.checkIn.toISOString().slice(0,10)}T14:00:00+05:00`);if(policies.some((p:any)=>p.kind==='NON_REFUNDABLE'||Date.now()>deadline-p.cutoff_hours*3600000))fail('POLICY_DENIED','Bron paytidagi qaytarish sharti ruxsat bermaydi',422);}
      if(await tx.refundRequest.findUnique({where:{bookingId:id}}))fail('REFUND_ALREADY_REQUESTED','Bu bron uchun qaytarish so‘rovi mavjud');
      const reserved=await tx.payoutItem.findFirst({where:{bookingId:id,active:true}});if(reserved){const payout=await tx.payout.findUniqueOrThrow({where:{id:reserved.payoutId}});if(payout.status!=='PAID')fail('PAYOUT_RESERVED','Avval o‘tkazma rezervini hal qiling');}
      const r=await tx.refundRequest.create({data:{bookingId:id,sanatoriumId:b.sanatoriumId,requestedBy:actor.id,amount:order.amount,reason:i.reason}});await audit(tx,actor.id,'refund.requested',r.id,b.sanatoriumId,undefined,{reason:i.reason,force:i.force});await emit(tx,'refund.requested',{booking_id:id,refund_id:r.id,recipient_ids:[]});return r;});
  }
  async refundDecision(actor:Actor,id:string,approve:boolean,body:unknown){requirePlatform(actor,'refunds.approve');parse(uuid,id);const i=parse(z.object({reason}).strict(),body);return this.db.atomic(async tx=>{const r=await tx.refundRequest.findUnique({where:{id}});if(!r)fail('NOT_FOUND','So‘rov topilmadi',404);await financialLock(tx,r.sanatoriumId);const current=await tx.refundRequest.findUniqueOrThrow({where:{id}});if(current.status!=='REQUESTED')fail('STATE_CONFLICT','Qaytarish holati o‘zgargan');
      if(approve)await refundReserve(tx,current);const changed=await tx.refundRequest.update({where:{id},data:{status:approve?'APPROVED':'REJECTED',decisionReason:i.reason}});await audit(tx,actor.id,approve?'refund.approved':'refund.rejected',id,r.sanatoriumId,undefined,i);return {...changed,next_action:approve?'Merchant kabinetida qaytarishni boshlang; natija provayder callbacki bilan tasdiqlanadi':null};});}
  async refundProcess(actor:Actor,id:string){requirePlatform(actor,'refunds.approve');parse(uuid,id);return this.db.atomic(async tx=>{const r=await tx.refundRequest.findUnique({where:{id}});if(!r)fail('NOT_FOUND','So‘rov topilmadi',404);await financialLock(tx,r.sanatoriumId);const changed=await tx.refundRequest.updateMany({where:{id,status:'APPROVED'},data:{status:'PROCESSING'}});if(!changed.count)fail('STATE_CONFLICT','Faqat ma’qullangan refundni boshlash mumkin');await audit(tx,actor.id,'refund.processing',id,r.sanatoriumId);return {status:'PROCESSING',confirmation_source:'provider_callback'};});}
  async cancelUnpaid(actor:Actor,id:string,body:unknown,key?:string){parse(uuid,id);const i=parse(z.object({reason}).strict(),body);return this.db.idempotent(actor.id,'booking.cancel',key,{id,...i},async tx=>{const b=await this.booking(tx,actor,id);if(b.status==='PAYMENT_PENDING')fail('PROVIDER_CANCELLATION_REQUIRED','To‘lov provayderda kutilmoqda. Yordam xizmatiga bekor qilish murojaatini yuboring');if(b.status!=='HOLD')fail('REFUND_REQUEST_REQUIRED','To‘langan bron uchun qaytarish so‘rovi kerak');await tx.booking.update({where:{id},data:{status:'CANCELLED',version:{increment:1}}});await tx.roomAllocation.updateMany({where:{bookingId:id,active:true},data:{active:false}});await tx.paymentOrder.updateMany({where:{bookingId:id,status:'CREATED'},data:{status:'CANCELLED'}});await tx.bookingEvent.create({data:{bookingId:id,actorId:actor.id,status:'CANCELLED',reason:i.reason}});await audit(tx,actor.id,'booking.cancelled',id,b.sanatoriumId);return {success:true};});}
  async refunds(actor:Actor,query:unknown){requirePlatform(actor,'refunds.approve');const i=parse(pageQuery,query);const[data,total]=await Promise.all([this.db.refundRequest.findMany({take:i.limit,skip:(i.page-1)*i.limit,orderBy:{createdAt:'desc'}}),this.db.refundRequest.count()]);return paged(data,total,i.page,i.limit);}
  async payoutCreate(actor:Actor,body:unknown,key?:string){requirePlatform(actor,'payouts.manage');const i=parse(z.object({sanatorium_id:uuid,booking_ids:z.array(uuid).min(1).max(100)}).strict(),body);if(new Set(i.booking_ids).size!==i.booking_ids.length)fail('DUPLICATE_BOOKING','Takroriy bron IDsi bor',422);
    return this.db.idempotent(actor.id,'payout.create',key,i,async tx=>{await financialLock(tx,i.sanatorium_id);const s=await tx.sanatorium.findUnique({where:{id:i.sanatorium_id}});if(!s?.bankRevisionId)fail('BANK_NOT_APPROVED','Tasdiqlangan bank rekviziti kerak');const bank=await tx.bankRevision.findUniqueOrThrow({where:{id:s.bankRevisionId}});if(bank.status!=='APPROVED')fail('BANK_NOT_APPROVED','Rekvizit tasdiqlanmagan');
      const bookings=await tx.booking.findMany({where:{id:{in:i.booking_ids},sanatoriumId:i.sanatorium_id}});if(bookings.length!==i.booking_ids.length)fail('NOT_FOUND','Bron topilmadi',404);const amounts:{id:string;amount:bigint}[]=[];
      for(const b of bookings){const payment=await tx.paymentOrder.findUnique({where:{bookingId:b.id}});if(b.status!=='CHECKED_OUT'||payment?.status!=='SUCCEEDED'||await tx.refundRequest.findFirst({where:{bookingId:b.id,status:{not:'REJECTED'}}})||await tx.payoutItem.findFirst({where:{bookingId:b.id,active:true}}))fail('PAYOUT_INELIGIBLE','Bron o‘tkazmaga yaroqli emas');const balance=await bookingBalance(tx,b.id,'SANATORIUM_PAYABLE');if(balance<=0n)fail('PAYOUT_INELIGIBLE','Bronning to‘lanadigan qoldig‘i yo‘q');amounts.push({id:b.id,amount:balance});}
      const amount=amounts.reduce((sum,a)=>sum+a.amount,0n);const payout=await tx.payout.create({data:{sanatoriumId:s.id,amount,bankSnapshot:{revision_id:bank.id,...bank.data as object}}});await tx.payoutItem.createMany({data:amounts.map(a=>({sanatoriumId:s.id,payoutId:payout.id,bookingId:a.id,amount:a.amount}))});await audit(tx,actor.id,'payout.created',payout.id,s.id,undefined,{amount,booking_ids:i.booking_ids});return payout;});}
  async payoutApprove(actor:Actor,id:string){requirePlatform(actor,'payouts.manage');parse(uuid,id);return this.db.atomic(async tx=>{const p=await tx.payout.findUnique({where:{id}});if(!p)fail('NOT_FOUND','O‘tkazma topilmadi',404);await financialLock(tx,p.sanatoriumId);const current=await tx.payout.findUniqueOrThrow({where:{id}});if(current.status!=='DRAFT')fail('STATE_CONFLICT','O‘tkazma holati o‘zgargan');const items=await tx.payoutItem.findMany({where:{payoutId:id,active:true}});for(const item of items){if(await tx.refundRequest.findFirst({where:{bookingId:item.bookingId,status:{not:'REJECTED'}}}))fail('REFUND_RESERVED','Bron refund uchun rezervlangan');await post(tx,`payout:start:${id}:${item.bookingId}`,'Payout ijroga olindi',[{account:'SANATORIUM_PAYABLE',debit:item.amount},{account:'PAYOUT_IN_TRANSIT',credit:item.amount}],p.sanatoriumId,item.bookingId);}await tx.payout.update({where:{id},data:{status:'APPROVED'}});await audit(tx,actor.id,'payout.approved',id,p.sanatoriumId);return {status:'APPROVED',bank_transfer_required:true};});}
  async payoutVerify(actor:Actor,id:string,body:unknown){requirePlatform(actor,'payouts.manage');parse(uuid,id);const i=parse(z.object({bank_reference:z.string().trim().min(5).max(150),evidence_asset_id:uuid,verified:z.literal(true)}).strict(),body);return this.db.atomic(async tx=>{const p=await tx.payout.findUnique({where:{id}});if(!p)fail('NOT_FOUND','O‘tkazma topilmadi',404);await financialLock(tx,p.sanatoriumId);const current=await tx.payout.findUniqueOrThrow({where:{id}});if(!['APPROVED','PROCESSING'].includes(current.status))fail('STATE_CONFLICT','O‘tkazma bank tasdig‘ini kutmayapti');const evidence=await tx.mediaAsset.findFirst({where:{id:i.evidence_asset_id,sanatoriumId:p.sanatoriumId,visibility:'PRIVATE'}});if(!evidence)fail('BANK_EVIDENCE_REQUIRED','Bank dalili faylini yuklang',422);const items=await tx.payoutItem.findMany({where:{payoutId:id,active:true}});for(const item of items)await post(tx,`payout:paid:${id}:${item.bookingId}`,'Bank o‘tkazmani tasdiqladi',[{account:'PAYOUT_IN_TRANSIT',debit:item.amount},{account:'BANK',credit:item.amount}],p.sanatoriumId,item.bookingId);const changed=await tx.payout.update({where:{id},data:{status:'PAID',bankReference:i.bank_reference,evidenceAssetId:evidence.id,paidAt:new Date()}});await audit(tx,actor.id,'payout.bank_verified',id,p.sanatoriumId,undefined,i);return changed;});}
  async payoutFail(actor:Actor,id:string,body:unknown){requirePlatform(actor,'payouts.manage');parse(uuid,id);const i=parse(z.object({reason}).strict(),body);return this.db.atomic(async tx=>{const p=await tx.payout.findUnique({where:{id}});if(!p)fail('NOT_FOUND','O‘tkazma topilmadi',404);await financialLock(tx,p.sanatoriumId);const current=await tx.payout.findUniqueOrThrow({where:{id}});if(!['DRAFT','APPROVED','PROCESSING'].includes(current.status))fail('STATE_CONFLICT','O‘tkazma yopilgan');const items=await tx.payoutItem.findMany({where:{payoutId:id,active:true}});if(current.status!=='DRAFT')for(const item of items){await post(tx,`payout:failed:${id}:${item.bookingId}`,'Payout rezervi qaytarildi',[{account:'PAYOUT_IN_TRANSIT',debit:item.amount},{account:'SANATORIUM_PAYABLE',credit:item.amount}],p.sanatoriumId,item.bookingId);const refund=await tx.refundRequest.findUnique({where:{bookingId:item.bookingId}});if(refund?.reserveAccount==='RECEIVABLE'&&['APPROVED','PROCESSING','SUCCEEDED'].includes(refund.status)){await post(tx,`refund:reclass:${refund.id}:${id}`,'Receivable qayta tasniflandi',[{account:'SANATORIUM_PAYABLE',debit:refund.amount},{account:'RECEIVABLE',credit:refund.amount}],p.sanatoriumId,item.bookingId);await tx.refundRequest.update({where:{id:refund.id},data:{reserveAccount:'SANATORIUM_PAYABLE'}});}}
      await tx.payoutItem.updateMany({where:{payoutId:id},data:{active:false}});await tx.payout.update({where:{id},data:{status:current.status==='DRAFT'?'CANCELLED':'FAILED',reason:i.reason}});await audit(tx,actor.id,'payout.failed',id,p.sanatoriumId,undefined,i);return {success:true};});}
  async payouts(actor:Actor,query:unknown){const i=parse(pageQuery.extend({sanatorium_id:uuid.optional()}).strict(),query);if(i.sanatorium_id)scope(actor,i.sanatorium_id,'payouts.read');const ids=tenantIds(actor,'payouts.read');const where=ids?{sanatoriumId:{in:i.sanatorium_id?[i.sanatorium_id]:ids}}:i.sanatorium_id?{sanatoriumId:i.sanatorium_id}:{};const[data,total]=await Promise.all([this.db.payout.findMany({where,take:i.limit,skip:(i.page-1)*i.limit,orderBy:{createdAt:'desc'}}),this.db.payout.count({where})]);return paged(data,total,i.page,i.limit);}
  async offline(actor:Actor,body:unknown,key?:string){const i=parse(z.object({booking_id:uuid,amount:positiveMoney,method:z.enum(['CASH','TERMINAL']),evidence:z.string().min(3).max(500),correction_of:uuid.optional()}).strict(),body);return this.db.idempotent(actor.id,'offline.record',key,i,async tx=>{const b=await this.booking(tx,actor,i.booking_id,'offline_payments.record');if(b.source==='APP'||!['CONFIRMED','CHECKED_IN','CHECKED_OUT'].includes(b.status))fail('OFFLINE_PAYMENT_DENIED','Faqat qo‘lda bronning joyida to‘lovini qayd eting');if(i.correction_of){const old=await tx.offlinePayment.findFirst({where:{id:i.correction_of,bookingId:b.id,status:'VERIFIED'}});if(!old)fail('NOT_FOUND','Tuzatiladigan to‘lov topilmadi',404);}if(BigInt(i.amount)>b.amount)fail('AMOUNT_EXCEEDS_DUE','Summa bron narxidan oshgan',422);const r=await tx.offlinePayment.create({data:{bookingId:b.id,sanatoriumId:b.sanatoriumId,amount:BigInt(i.amount),method:i.method,evidence:i.evidence,recordedBy:actor.id,correctionOf:i.correction_of}});await audit(tx,actor.id,'offline.recorded',r.id,b.sanatoriumId);return r;});}
  async offlineVerify(actor:Actor,id:string){parse(uuid,id);return this.db.atomic(async tx=>{const r=await tx.offlinePayment.findUnique({where:{id}});if(!r)fail('NOT_FOUND','To‘lov topilmadi',404);scope(actor,r.sanatoriumId,'offline_payments.verify');await financialLock(tx,r.sanatoriumId);const current=await tx.offlinePayment.findUniqueOrThrow({where:{id}});if(current.status!=='UNVERIFIED')fail('STATE_CONFLICT','To‘lov holati o‘zgargan');if(r.recordedBy===actor.id)fail('SECOND_REVIEW_REQUIRED','Boshqa vakolatli xodim tasdiqlasin',403);const b=await tx.booking.findUniqueOrThrow({where:{id:r.bookingId}});const verified=await tx.offlinePayment.aggregate({where:{bookingId:b.id,status:'VERIFIED',...(r.correctionOf?{id:{not:r.correctionOf}}:{})},_sum:{amount:true}});if((verified._sum.amount??0n)+r.amount>b.amount)fail('AMOUNT_EXCEEDS_DUE','Tasdiqlangan to‘lovlar bron narxidan oshgan');if(r.correctionOf){const old=await tx.offlinePayment.updateMany({where:{id:r.correctionOf,status:'VERIFIED'},data:{status:'CORRECTED'}});if(!old.count)fail('STATE_CONFLICT','Avvalgi to‘lov allaqachon tuzatilgan');}const changed=await tx.offlinePayment.update({where:{id},data:{status:'VERIFIED',verifiedBy:actor.id}});await audit(tx,actor.id,'offline.verified',id,r.sanatoriumId);return changed;});}
}
