BEGIN;
CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE "User" ADD CONSTRAINT user_kind CHECK (kind IN ('SUPERADMIN','STAFF','CUSTOMER'));
ALTER TABLE "User" ADD CONSTRAINT user_status CHECK (status IN ('ACTIVE','BLOCKED'));
ALTER TABLE "Membership" ADD CONSTRAINT membership_user FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "Membership" ADD CONSTRAINT membership_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);
ALTER TABLE "Membership" ADD CONSTRAINT membership_role CHECK (role IN ('DIRECTOR','RECEPTION'));
ALTER TABLE "Membership" ADD CONSTRAINT membership_status CHECK (status IN ('PENDING_APPROVAL','ACTIVE','REJECTED','BLOCKED','REVOKED'));
CREATE UNIQUE INDEX one_active_director ON "Membership"("sanatoriumId") WHERE role='DIRECTOR' AND status='ACTIVE';
ALTER TABLE "Session" ADD CONSTRAINT session_account_fk FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "SanatoriumRevision" ADD CONSTRAINT revision_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);
ALTER TABLE "Sanatorium" ADD CONSTRAINT public_revision_tenant FOREIGN KEY ("publicRevisionId",id) REFERENCES "SanatoriumRevision"(id,"sanatoriumId");
ALTER TABLE "BankRevision" ADD CONSTRAINT bank_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);
ALTER TABLE "Sanatorium" ADD CONSTRAINT bank_revision_tenant FOREIGN KEY ("bankRevisionId",id) REFERENCES "BankRevision"(id,"sanatoriumId");
ALTER TABLE "RoomType" ADD CONSTRAINT room_type_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);
ALTER TABLE "RoomType" ADD CONSTRAINT room_capacity CHECK ("maxGuests">0 AND "maxAdults">0 AND "maxChildren">=0 AND "maxAdults"<="maxGuests" AND "maxChildren"<="maxGuests");
ALTER TABLE "Room" ADD CONSTRAINT room_type_scope FOREIGN KEY ("roomTypeId","sanatoriumId") REFERENCES "RoomType"(id,"sanatoriumId");
ALTER TABLE "RatePlan" ADD CONSTRAINT rate_type_scope FOREIGN KEY ("roomTypeId","sanatoriumId") REFERENCES "RoomType"(id,"sanatoriumId");
ALTER TABLE "RatePlan" ADD CONSTRAINT rate_policy FOREIGN KEY ("policyId") REFERENCES "RefundPolicy"(id);
ALTER TABLE "RatePlan" ADD CONSTRAINT rate_amount CHECK ("baseAmount">0 AND "minNights">0 AND "maxNights">="minNights" AND mode IN ('ROOM','PERSON'));
ALTER TABLE "DailyRate" ADD CONSTRAINT daily_rate_scope FOREIGN KEY ("ratePlanId","sanatoriumId") REFERENCES "RatePlan"(id,"sanatoriumId");
ALTER TABLE "DailyRate" ADD CONSTRAINT daily_rate_amount CHECK (amount>0);
ALTER TABLE "Discount" ADD CONSTRAINT discount_valid CHECK ("endsAt">"startsAt" AND value>0 AND "minAmount">=0 AND (kind IN ('FIXED','PERCENT')) AND (kind<>'PERCENT' OR value<=100));
ALTER TABLE "Quote" ADD CONSTRAINT quote_user FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "Booking" ADD CONSTRAINT booking_quote_scope FOREIGN KEY ("quoteId","sanatoriumId") REFERENCES "Quote"(id,"sanatoriumId");
ALTER TABLE "Booking" ADD CONSTRAINT booking_user FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "Booking" ADD CONSTRAINT booking_dates CHECK ("checkOut">"checkIn" AND amount>0);
ALTER TABLE "BookingItem" ADD CONSTRAINT item_booking_scope FOREIGN KEY ("bookingId","sanatoriumId") REFERENCES "Booking"(id,"sanatoriumId");
ALTER TABLE "BookingItem" ADD CONSTRAINT item_room_scope FOREIGN KEY ("roomId","sanatoriumId") REFERENCES "Room"(id,"sanatoriumId");
ALTER TABLE "BookingItem" ADD CONSTRAINT item_rate_scope FOREIGN KEY ("ratePlanId","sanatoriumId") REFERENCES "RatePlan"(id,"sanatoriumId");
ALTER TABLE "BookingItem" ADD CONSTRAINT item_type_scope FOREIGN KEY ("roomTypeId","sanatoriumId") REFERENCES "RoomType"(id,"sanatoriumId");
ALTER TABLE "RoomAllocation" ADD CONSTRAINT allocation_room_scope FOREIGN KEY ("roomId","sanatoriumId") REFERENCES "Room"(id,"sanatoriumId");
ALTER TABLE "RoomAllocation" ADD CONSTRAINT allocation_booking_scope FOREIGN KEY ("bookingId","sanatoriumId") REFERENCES "Booking"(id,"sanatoriumId");
ALTER TABLE "RoomAllocation" ADD CONSTRAINT allocation_dates CHECK ("checkOut">"checkIn");
ALTER TABLE "RoomAllocation" ADD CONSTRAINT room_dates_do_not_overlap EXCLUDE USING gist ("roomId" WITH =, daterange("checkIn","checkOut",'[)') WITH &&) WHERE (active);
ALTER TABLE "BookingEvent" ADD CONSTRAINT booking_event_fk FOREIGN KEY ("bookingId") REFERENCES "Booking"(id);
ALTER TABLE "MediaAsset" ADD CONSTRAINT media_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);
ALTER TABLE "MediaAsset" ADD CONSTRAINT media_revision_scope FOREIGN KEY ("revisionId","sanatoriumId") REFERENCES "SanatoriumRevision"(id,"sanatoriumId");
ALTER TABLE "PaymentOrder" ADD CONSTRAINT payment_booking_scope FOREIGN KEY ("bookingId","sanatoriumId") REFERENCES "Booking"(id,"sanatoriumId");
ALTER TABLE "PaymentOrder" ADD CONSTRAINT payment_source CHECK (("bookingId" IS NOT NULL)::int + ("invoiceId" IS NOT NULL)::int = 1 AND amount>0);
ALTER TABLE "ProviderTransaction" ADD CONSTRAINT transaction_order_fk FOREIGN KEY ("orderId") REFERENCES "PaymentOrder"(id);
CREATE UNIQUE INDEX one_live_provider_transaction ON "ProviderTransaction"("orderId") WHERE state IN (1,2);
ALTER TABLE "LedgerLine" ADD CONSTRAINT ledger_journal_fk FOREIGN KEY ("journalId") REFERENCES "LedgerJournal"(id);
ALTER TABLE "LedgerLine" ADD CONSTRAINT ledger_line_amount CHECK (debit>=0 AND credit>=0 AND ((debit>0 AND credit=0) OR (credit>0 AND debit=0)));
ALTER TABLE "RefundRequest" ADD CONSTRAINT refund_booking_scope FOREIGN KEY ("bookingId","sanatoriumId") REFERENCES "Booking"(id,"sanatoriumId");
ALTER TABLE "RefundRequest" ADD CONSTRAINT refund_amount CHECK (amount>0);
ALTER TABLE "PayoutItem" ADD CONSTRAINT payout_item_scope FOREIGN KEY ("payoutId","sanatoriumId") REFERENCES "Payout"(id,"sanatoriumId");
ALTER TABLE "PayoutItem" ADD CONSTRAINT payout_booking_scope FOREIGN KEY ("bookingId","sanatoriumId") REFERENCES "Booking"(id,"sanatoriumId");
CREATE UNIQUE INDEX one_active_payout_per_booking ON "PayoutItem"("bookingId") WHERE active;
ALTER TABLE "OfflinePayment" ADD CONSTRAINT offline_booking_scope FOREIGN KEY ("bookingId","sanatoriumId") REFERENCES "Booking"(id,"sanatoriumId");
ALTER TABLE "OfflinePayment" ADD CONSTRAINT offline_positive CHECK (amount>0);
ALTER TABLE "Subscription" ADD CONSTRAINT subscription_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);
ALTER TABLE "Subscription" ADD CONSTRAINT subscription_plan FOREIGN KEY ("planId") REFERENCES "SubscriptionPlan"(id);
ALTER TABLE "Invoice" ADD CONSTRAINT invoice_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);
ALTER TABLE "Invoice" ADD CONSTRAINT invoice_valid CHECK (amount>0 AND "endsAt">"startsAt");
ALTER TABLE "AdCampaign" ADD CONSTRAINT campaign_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);
ALTER TABLE "AdCampaign" ADD CONSTRAINT campaign_invoice FOREIGN KEY ("invoiceId") REFERENCES "Invoice"(id);
ALTER TABLE "AdEvent" ADD CONSTRAINT campaign_event FOREIGN KEY ("campaignId") REFERENCES "AdCampaign"(id);
ALTER TABLE "MessageRecipient" ADD CONSTRAINT recipient_message FOREIGN KEY ("messageId") REFERENCES "Message"(id);
ALTER TABLE "MessageRecipient" ADD CONSTRAINT recipient_user FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "SurveyResponse" ADD CONSTRAINT survey_response_fk FOREIGN KEY ("surveyId") REFERENCES "Survey"(id);
ALTER TABLE "NotificationDelivery" ADD CONSTRAINT notification_event_fk FOREIGN KEY ("eventId") REFERENCES "OutboxEvent"(id);
ALTER TABLE "NotificationDelivery" ADD CONSTRAINT notification_user_fk FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "Review" ADD CONSTRAINT review_booking_scope FOREIGN KEY ("bookingId","sanatoriumId") REFERENCES "Booking"(id,"sanatoriumId");
ALTER TABLE "Review" ADD CONSTRAINT review_rating CHECK (rating BETWEEN 1 AND 5);
ALTER TABLE "SupportMessage" ADD CONSTRAINT support_ticket_fk FOREIGN KEY ("ticketId") REFERENCES "SupportTicket"(id);
ALTER TABLE "Favorite" ADD CONSTRAINT favorite_user FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "Favorite" ADD CONSTRAINT favorite_tenant FOREIGN KEY ("sanatoriumId") REFERENCES "Sanatorium"(id);

CREATE FUNCTION verify_journal_balance() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target uuid; debit_sum bigint; credit_sum bigint; line_count bigint;
BEGIN
  IF TG_TABLE_NAME='LedgerJournal' THEN target:=NEW.id; ELSE target:=NEW."journalId"; END IF;
  SELECT coalesce(sum(debit),0),coalesce(sum(credit),0),count(*) INTO debit_sum,credit_sum,line_count FROM "LedgerLine" WHERE "journalId"=target;
  IF line_count<2 OR debit_sum<>credit_sum THEN RAISE EXCEPTION 'Unbalanced ledger journal %',target USING ERRCODE='23514'; END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER journal_balance AFTER INSERT ON "LedgerJournal" DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION verify_journal_balance();
CREATE CONSTRAINT TRIGGER line_balance AFTER INSERT ON "LedgerLine" DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION verify_journal_balance();

CREATE FUNCTION immutable_history() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Immutable history: use a reversal or new event' USING ERRCODE='23514'; END $$;
CREATE TRIGGER immutable_journal BEFORE UPDATE OR DELETE ON "LedgerJournal" FOR EACH ROW EXECUTE FUNCTION immutable_history();
CREATE TRIGGER immutable_line BEFORE UPDATE OR DELETE ON "LedgerLine" FOR EACH ROW EXECUTE FUNCTION immutable_history();
CREATE TRIGGER immutable_audit BEFORE UPDATE OR DELETE ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION immutable_history();
CREATE TRIGGER immutable_booking_event BEFORE UPDATE OR DELETE ON "BookingEvent" FOR EACH ROW EXECUTE FUNCTION immutable_history();
COMMIT;
