import { Inject,Injectable } from '@nestjs/common';
import { z } from 'zod';
import { Db,audit,emit,lock } from '../common/db';
import { parse,uuid,version,reason,fail,pageQuery,paged } from '../common/errors';
import { Actor,scope,tenantIds,requirePlatform } from '../auth/permissions';

@Injectable()
export class EngagementService{
  constructor(@Inject(Db) readonly db:Db){}
  private async recipients(actor:Actor,ids:string[]){
    if(actor.kind==='CUSTOMER')fail('PERMISSION_DENIED','Ruxsat yo‘q',403);const users=await this.db.user.findMany({where:{id:{in:ids},status:'ACTIVE',kind:'STAFF'},select:{id:true}});if(users.length!==new Set(ids).size)fail('RECIPIENT_INVALID','Qabul qiluvchini tekshiring',422);
    if(actor.kind!=='SUPERADMIN'){const tenants=tenantIds(actor,'messages.send')??[];const members=await this.db.membership.findMany({where:{userId:{in:ids},sanatoriumId:{in:tenants},status:'ACTIVE'},select:{userId:true}});if(new Set(members.map(m=>m.userId)).size!==new Set(ids).size)fail('PERMISSION_DENIED','Boshqa sanatoriyaga yubora olmaysiz',403);}return [...new Set(ids)];
  }
  async broadcast(actor:Actor,body:unknown){requirePlatform(actor,'announcements.broadcast');const i=parse(z.object({sanatorium_ids:z.array(uuid).max(100).optional(),title:z.string().min(2).max(150),body:z.string().min(1).max(10000),kind:z.enum(['MESSAGE','WARNING']),asset_ids:z.array(uuid).max(10).default([])}).strict(),body);const members=await this.db.membership.findMany({where:{status:'ACTIVE',...(i.sanatorium_ids?{sanatoriumId:{in:i.sanatorium_ids}}:{})},select:{userId:true}});return this.send(actor,{title:i.title,body:i.body,kind:i.kind,asset_ids:i.asset_ids,recipient_ids:[...new Set(members.map(m=>m.userId))]});}
  async send(actor:Actor,body:unknown){const i=parse(z.object({title:z.string().min(2).max(150),body:z.string().min(1).max(10000),kind:z.enum(['MESSAGE','WARNING']).default('MESSAGE'),asset_ids:z.array(uuid).max(10).default([]),recipient_ids:z.array(uuid).max(1000)}).strict(),body);const ids=await this.recipients(actor,i.recipient_ids);
    for(const id of i.asset_ids){const file=await this.db.mediaAsset.findUnique({where:{id}});if(!file)fail('NOT_FOUND','Fayl topilmadi',404);scope(actor,file.sanatoriumId,'sanatorium.profile.edit');}
    return this.db.atomic(async tx=>{const m=await tx.message.create({data:{senderId:actor.id,title:i.title,body:i.body,kind:i.kind,assetIds:i.asset_ids}});await tx.messageRecipient.createMany({data:ids.map(userId=>({messageId:m.id,userId}))});await emit(tx,'message.created',{message_id:m.id,recipient_ids:ids});await audit(tx,actor.id,'message.sent',m.id,undefined,undefined,{recipient_count:ids.length});return m;});}
  async messages(actor:Actor,query:unknown){const i=parse(pageQuery,query);const receipts=await this.db.messageRecipient.findMany({where:{userId:actor.id},skip:(i.page-1)*i.limit,take:i.limit,orderBy:{id:'desc'}});const messages=await this.db.message.findMany({where:{id:{in:receipts.map(r=>r.messageId)}}});return paged(receipts.map(r=>({...r,message:messages.find(m=>m.id===r.messageId)})),await this.db.messageRecipient.count({where:{userId:actor.id}}),i.page,i.limit);}
  async receipt(actor:Actor,id:string,body:unknown){parse(uuid,id);const i=parse(z.object({accepted:z.boolean().default(false)}).strict(),body);const r=await this.db.messageRecipient.findUnique({where:{messageId_userId:{messageId:id,userId:actor.id}}});if(!r)fail('NOT_FOUND','Xabar topilmadi',404);return this.db.messageRecipient.update({where:{id:r.id},data:{readAt:r.readAt??new Date(),acceptedAt:i.accepted?(r.acceptedAt??new Date()):r.acceptedAt}});}
  async task(actor:Actor,body:unknown){const i=parse(z.object({sanatorium_id:uuid,assigned_to:uuid,title:z.string().min(2).max(150),body:z.string().min(1).max(5000),due_at:z.iso.datetime()}).strict(),body);scope(actor,i.sanatorium_id,'tasks.manage');if(!await this.db.membership.findFirst({where:{sanatoriumId:i.sanatorium_id,userId:i.assigned_to,status:'ACTIVE'}}))fail('NOT_FOUND','Faol xodim topilmadi',404);return this.db.atomic(async tx=>{const t=await tx.task.create({data:{sanatoriumId:i.sanatorium_id,assignedBy:actor.id,assignedTo:i.assigned_to,title:i.title,body:i.body,dueAt:new Date(i.due_at)}});await emit(tx,'task.assigned',{task_id:t.id,recipient_ids:[i.assigned_to]});await audit(tx,actor.id,'task.assigned',t.id,i.sanatorium_id);return t;});}
  async tasks(actor:Actor){const ids=tenantIds(actor,'tasks.manage');const where=actor.kind==='SUPERADMIN'?{}:{OR:[{assignedTo:actor.id},{sanatoriumId:{in:ids??[]}}]};return this.db.task.findMany({where,orderBy:{dueAt:'asc'},take:200});}
  async taskReply(actor:Actor,id:string,body:unknown){parse(uuid,id);const i=parse(z.object({version,status:z.enum(['ACCEPTED','COMPLETED']),reply:z.string().max(5000).optional()}).strict(),body);return this.db.atomic(async tx=>{const t=await tx.task.findUnique({where:{id}});if(!t||(t.assignedTo!==actor.id&&actor.kind!=='SUPERADMIN'))fail('NOT_FOUND','Vazifa topilmadi',404);scope(actor,t.sanatoriumId);const from=i.status==='ACCEPTED'?'ASSIGNED':'ACCEPTED';const changed=await tx.task.updateMany({where:{id,version:i.version,status:from},data:{status:i.status,reply:i.reply,version:{increment:1}}});if(!changed.count)fail('VERSION_CONFLICT','Vazifa holati o‘zgargan');await audit(tx,actor.id,'task.updated',id,t.sanatoriumId,undefined,i);return tx.task.findUniqueOrThrow({where:{id}});});}
  async survey(actor:Actor,body:unknown){requirePlatform(actor,'announcements.broadcast');const i=parse(z.object({title:z.string().min(2).max(150),recipient_ids:z.array(uuid).max(1000),questions:z.array(z.object({id:z.string().regex(/^[a-z_]{1,40}$/),label:z.string().min(1).max(300),type:z.enum(['TEXT','BOOLEAN','NUMBER']),required:z.boolean()}).strict()).min(1).max(30)}).strict(),body);const ids=await this.recipients(actor,i.recipient_ids);if(new Set(i.questions.map(q=>q.id)).size!==i.questions.length)fail('QUESTION_ID_DUPLICATE','Savol IDlari takrorlanmasin',422);return this.db.atomic(async tx=>{await lock(tx,`survey:${actor.id}:${i.title}`);const previous=await tx.survey.findFirst({where:{createdBy:actor.id,title:i.title},orderBy:{version:'desc'}});const s=await tx.survey.create({data:{title:i.title,createdBy:actor.id,questions:i.questions,recipientIds:ids,version:(previous?.version??0)+1}});await emit(tx,'survey.created',{survey_id:s.id,recipient_ids:ids});await audit(tx,actor.id,'survey.created',s.id);return s;});}
  async surveys(actor:Actor){return this.db.survey.findMany({where:actor.kind==='SUPERADMIN'?{}:{recipientIds:{has:actor.id}},take:100,orderBy:{createdAt:'desc'}});}
  async answer(actor:Actor,id:string,body:unknown){parse(uuid,id);const i=parse(z.object({version,answers:z.record(z.string(),z.union([z.string().max(5000),z.boolean(),z.number()]))}).strict(),body);const s=await this.db.survey.findUnique({where:{id}});if(!s||!s.recipientIds.includes(actor.id))fail('NOT_FOUND','Anketa topilmadi',404);if(s.version!==i.version)fail('VERSION_CONFLICT','Anketa versiyasi mos emas');const questions=s.questions as {id:string;type:string;required:boolean}[];for(const q of questions){const value=i.answers[q.id];if(q.required&&(value===undefined||value===''))fail('ANSWER_REQUIRED',`${q.id} savoliga javob kerak`,422);if(value!==undefined&&typeof value!=={TEXT:'string',BOOLEAN:'boolean',NUMBER:'number'}[q.type])fail('ANSWER_TYPE_INVALID',`${q.id} javob turini tekshiring`,422);}if(Object.keys(i.answers).some(k=>!questions.some(q=>q.id===k)))fail('ANSWER_UNKNOWN','Noma’lum savolga javob bor',422);return this.db.surveyResponse.create({data:{surveyId:id,userId:actor.id,surveyVersion:s.version,answers:i.answers}});}
  async review(actor:Actor,body:unknown){const i=parse(z.object({booking_id:uuid,rating:z.number().int().min(1).max(5),text:z.string().trim().min(3).max(3000)}).strict(),body);const b=await this.db.booking.findUnique({where:{id:i.booking_id}});if(!b||b.userId!==actor.id||b.status!=='CHECKED_OUT')fail('REVIEW_NOT_ALLOWED','Faqat o‘z yakunlangan yashashingiz uchun sharh yozing',403);return this.db.review.create({data:{bookingId:b.id,sanatoriumId:b.sanatoriumId,userId:actor.id,rating:i.rating,text:i.text}});}
  async reviewList(actor:Actor,query:unknown){const i=parse(pageQuery.extend({sanatorium_id:uuid.optional()}).strict(),query);if(i.sanatorium_id)scope(actor,i.sanatorium_id,'reviews.reply');const ids=tenantIds(actor,'reviews.reply');const where={...(ids?{sanatoriumId:{in:ids}}:{}),...(i.sanatorium_id?{sanatoriumId:i.sanatorium_id}:{})};const [data,total]=await Promise.all([this.db.review.findMany({where,take:i.limit,skip:(i.page-1)*i.limit,orderBy:{createdAt:'desc'}}),this.db.review.count({where})]);return paged(data,total,i.page,i.limit);}
  async reviewReply(actor:Actor,id:string,body:unknown){parse(uuid,id);const i=parse(z.object({reply:z.string().trim().min(3).max(3000)}).strict(),body);const r=await this.db.review.findUnique({where:{id}});if(!r)fail('NOT_FOUND','Sharh topilmadi',404);scope(actor,r.sanatoriumId,'reviews.reply');return this.db.atomic(async tx=>{const result=await tx.review.update({where:{id},data:{reply:i.reply}});await audit(tx,actor.id,'review.replied',id,r.sanatoriumId);return result;});}
  async moderateReview(actor:Actor,id:string,body:unknown){requirePlatform(actor,'reviews.moderate');parse(uuid,id);const i=parse(z.object({status:z.enum(['PUBLISHED','HIDDEN']),reason}).strict(),body);return this.db.atomic(async tx=>{const r=await tx.review.update({where:{id},data:{status:i.status,moderationReason:i.reason}});await audit(tx,actor.id,'review.moderated',id,r.sanatoriumId,undefined,i);return r;});}
  async ticket(actor:Actor,body:unknown){const i=parse(z.object({title:z.string().min(2).max(150),text:z.string().min(3).max(5000),booking_id:uuid.optional(),sanatorium_id:uuid.optional()}).strict(),body);let tenant=i.sanatorium_id;if(i.booking_id){const b=await this.db.booking.findUnique({where:{id:i.booking_id}});if(!b)fail('NOT_FOUND','Bron topilmadi',404);if(actor.kind==='CUSTOMER'){if(b.userId!==actor.id)fail('NOT_FOUND','Bron topilmadi',404);}else scope(actor,b.sanatoriumId,'support.read');tenant=b.sanatoriumId;}else if(tenant&&actor.kind!=='CUSTOMER')scope(actor,tenant,'support.read');return this.db.atomic(async tx=>{const t=await tx.supportTicket.create({data:{userId:actor.id,sanatoriumId:tenant,bookingId:i.booking_id,title:i.title}});await tx.supportMessage.create({data:{ticketId:t.id,userId:actor.id,text:i.text}});await audit(tx,actor.id,'support.opened',t.id,tenant);return t;});}
  async tickets(actor:Actor){const ids=tenantIds(actor,'support.read');return this.db.supportTicket.findMany({where:actor.kind==='SUPERADMIN'?{}:actor.kind==='CUSTOMER'?{userId:actor.id}:{OR:[{userId:actor.id},{sanatoriumId:{in:ids??[]}}]},take:200,orderBy:{createdAt:'desc'}});}
  async ticketGet(actor:Actor,id:string){parse(uuid,id);const t=await this.db.supportTicket.findUnique({where:{id}});if(!t)fail('NOT_FOUND','Murojaat topilmadi',404);if(actor.kind==='CUSTOMER'){if(t.userId!==actor.id)fail('NOT_FOUND','Murojaat topilmadi',404);}else if(t.userId!==actor.id&&actor.kind!=='SUPERADMIN'){if(!t.sanatoriumId)fail('NOT_FOUND','Murojaat topilmadi',404);scope(actor,t.sanatoriumId,'support.read');}return {...t,messages:await this.db.supportMessage.findMany({where:{ticketId:id},orderBy:{createdAt:'asc'}})};}
  async ticketReply(actor:Actor,id:string,body:unknown){const i=parse(z.object({text:z.string().min(1).max(5000),close:z.boolean().default(false)}).strict(),body);const t=await this.ticketGet(actor,id);if(i.close&&actor.kind!=='SUPERADMIN')fail('PERMISSION_DENIED','Murojaatni support yopadi',403);return this.db.atomic(async tx=>{const m=await tx.supportMessage.create({data:{ticketId:id,userId:actor.id,text:i.text}});if(i.close)await tx.supportTicket.update({where:{id},data:{status:'CLOSED'}});await emit(tx,'support.replied',{recipient_ids:[t.userId],ticket_id:id});return m;});}
  async notifications(actor:Actor){return this.db.notificationDelivery.findMany({where:{userId:actor.id,channel:'IN_APP'},take:100,orderBy:{id:'desc'}});}
  async notificationRead(actor:Actor,id:string){parse(uuid,id);const r=await this.db.notificationDelivery.updateMany({where:{id,userId:actor.id},data:{readAt:new Date()}});if(!r.count)fail('NOT_FOUND','Bildirishnoma topilmadi',404);return {success:true};}
}
