import { Inject,Injectable } from '@nestjs/common';
import { z } from 'zod';
import { Db,audit,bodyHash,type Tx } from '../common/db';
import { parse,uuid,positiveMoney,money,fail,pageQuery,paged,reason } from '../common/errors';
import { Actor,scope,requirePlatform } from '../auth/permissions';
import { post } from '../ledger/ledger';
import { financialLock } from '../payments/payment.service';

@Injectable()
export class ReportsService{
  constructor(@Inject(Db) readonly db:Db){}
  async report(actor:Actor,query:unknown,global=false){const i=parse(z.object({sanatorium_id:uuid.optional(),from:z.iso.date(),to:z.iso.date(),booking_basis:z.enum(['CREATED','PAYMENT','SERVICE']).default('SERVICE'),financial:z.enum(['true','false']).default('false')}).strict(),query);if(i.to<=i.from||(Date.parse(i.to)-Date.parse(i.from))>366*86400000)fail('DATE_RANGE_INVALID','Davr 1–366 kun bo‘lsin',422);if(global)requirePlatform(actor,'platform.reports');const tenant=i.sanatorium_id??(global?undefined:actor.memberships.find(m=>m.status==='ACTIVE')?.sanatoriumId);if(!global&&!tenant)fail('TENANT_REQUIRED','Sanatoriyani tanlang',422);if(tenant)scope(actor,tenant,i.financial==='true'?'reports.financial.read':'reports.operational.read');
    const from=new Date(`${i.from}T00:00:00+05:00`),to=new Date(`${i.to}T00:00:00+05:00`);const checkIn=new Date(i.from),checkOut=new Date(i.to);const where=tenant?{sanatoriumId:tenant}:{};
    const payments=await this.db.paymentOrder.findMany({where:{...where,purpose:'BOOKING',status:'SUCCEEDED',paidAt:{gte:from,lt:to}}});const countWhere:any={...where};if(i.booking_basis==='CREATED')countWhere.createdAt={gte:from,lt:to};else if(i.booking_basis==='PAYMENT')countWhere.id={in:payments.map(p=>p.bookingId!).filter(Boolean)};else{countWhere.checkIn={lt:checkOut};countWhere.checkOut={gt:checkIn};}
    const [bookings,service,rooms,maintenance]=await Promise.all([this.db.booking.findMany({where:countWhere}),this.db.booking.findMany({where:{...where,status:{in:['CONFIRMED','CHECKED_IN','CHECKED_OUT']},checkIn:{lt:checkOut},checkOut:{gt:checkIn}}}),this.db.room.findMany({where:{...where,active:true}}),this.db.roomAllocation.findMany({where:{...where,kind:'MAINTENANCE',active:true,checkIn:{lt:checkOut},checkOut:{gt:checkIn}}})]);
    const items=await this.db.bookingItem.findMany({where:{bookingId:{in:service.map(b=>b.id)}}});const clip=(a:Date,b:Date)=>Math.max(0,(Math.min(b.getTime(),checkOut.getTime())-Math.max(a.getTime(),checkIn.getTime()))/86400000);const blocked=maintenance.reduce((n,m)=>n+clip(m.checkIn,m.checkOut),0);const denominator=rooms.length*(checkOut.getTime()-checkIn.getTime())/86400000-blocked;let roomNights=0,guestNights=0;for(const b of service){const n=clip(b.checkIn,b.checkOut);const group=items.filter(i=>i.bookingId===b.id);roomNights+=n*group.length;guestNights+=n*group.reduce((sum,i)=>sum+i.adults+i.childrenAges.length,0);}
    const result:any={period:{from:i.from,to:i.to,timezone:'Asia/Tashkent',booking_basis:i.booking_basis,payment_basis:'paid_at',service_basis:'overlap'},bookings:bookings.length,booking_statuses:bookings.reduce((a:any,b)=>({...a,[b.status]:(a[b.status]??0)+1}),{}),room_nights:roomNights,guest_nights:guestNights,sellable_room_nights:Math.max(0,denominator),occupancy:denominator>0?roomNights/denominator:0};
    if(i.financial==='true'||global){const refunds=await this.db.refundRequest.findMany({where:{...where,status:'SUCCEEDED',completedAt:{gte:from,lt:to}}});const gmv=payments.reduce((n,p)=>n+p.amount,0n);const refunded=refunds.reduce((n,r)=>n+r.amount,0n);const journals=await this.db.ledgerJournal.findMany({where:{...where,createdAt:{lt:to}},select:{id:true,createdAt:true}});const lines=await this.db.ledgerLine.findMany({where:{journalId:{in:journals.map(j=>j.id)}}});const net=(account:string)=>lines.filter(l=>l.account===account).reduce((n,l)=>n+l.credit-l.debit,0n);const periodIds=new Set(journals.filter(j=>j.createdAt>=from).map(j=>j.id));const revenue=lines.filter(l=>periodIds.has(l.journalId)&&['AD_REVENUE','SUBSCRIPTION_REVENUE'].includes(l.account)).reduce((n,l)=>n+l.credit-l.debit,0n);Object.assign(result,{gmv:gmv.toString(),refunds:refunded.toString(),net_online_receipts:(gmv-refunded).toString(),sanatorium_payable:net('SANATORIUM_PAYABLE').toString(),refund_payable:net('REFUND_PAYABLE').toString(),payout_in_transit:net('PAYOUT_IN_TRANSIT').toString(),receivable:(-net('RECEIVABLE')).toString(),deferred_service_revenue:net('DEFERRED_SERVICE_REVENUE').toString(),...(global?{platform_revenue:revenue.toString()}:{}),currency:'UZS',minor_unit:'tiyin'});}return result;
  }
  async export(actor:Actor,query:unknown){const q=query as any;const id=q.sanatorium_id??actor.memberships.find(m=>m.status==='ACTIVE')?.sanatoriumId;if(id)scope(actor,id,'reports.export');else requirePlatform(actor,'platform.reports');const report=await this.report(actor,query,actor.kind==='SUPERADMIN'&&!id);await this.db.atomic(tx=>audit(tx,actor.id,'report.exported',id??'platform',id));const safe=(s:string)=>`"${(/^[=+\-@]/.test(s)?"'":'')+s.replace(/"/g,'""')}"`;return 'ko‘rsatkich,qiymat\n'+Object.entries(report).filter(([,v])=>typeof v!=='object').map(([k,v])=>`${safe(k)},${safe(String(v))}`).join('\n');}
  async audit(actor:Actor,query:unknown){requirePlatform(actor,'audit.read');const i=parse(pageQuery,query);const[data,total]=await Promise.all([this.db.auditLog.findMany({take:i.limit,skip:(i.page-1)*i.limit,orderBy:{createdAt:'desc'}}),this.db.auditLog.count()]);return paged(data,total,i.page,i.limit);}
  async reconcile(actor:Actor,body:unknown){requirePlatform(actor,'reconciliation.manage');const i=parse(z.object({kind:z.enum(['PROVIDER','BANK']),evidence_asset_id:uuid.optional(),rows:z.array(z.object({provider_id:z.string().min(8).max(64),order_id:uuid,amount:positiveMoney,state:z.number().int().refine(n=>[1,2,-1,-2].includes(n)),bank_reference:z.string().min(5).max(150).optional(),fee:money.default('0')}).strict()).min(1).max(5000)}).strict(),body);if(i.kind==='BANK'&&!i.evidence_asset_id)fail('BANK_EVIDENCE_REQUIRED','Bank reestri dalili kerak',422);if(i.evidence_asset_id&&!await this.db.mediaAsset.findFirst({where:{id:i.evidence_asset_id,visibility:'PRIVATE'}}))fail('NOT_FOUND','Dalil topilmadi',404);
    return this.db.atomic(async tx=>{const digest=bodyHash(i);const old=await tx.reconciliationImport.findUnique({where:{hash:digest}});if(old)return old;const record=await tx.reconciliationImport.create({data:{hash:digest,kind:i.kind,importedBy:actor.id,data:i}});
      for(const row of i.rows){const p=await tx.providerTransaction.findUnique({where:{provider_providerId:{provider:'PAYME',providerId:row.provider_id}}});if(!p||p.orderId!==row.order_id||p.amount!==BigInt(row.amount)||p.state!==row.state){await tx.reconciliationDifference.create({data:{importId:record.id,orderId:p?.orderId,data:{...row,reason:'AMOUNT_STATE_OR_ORDER_MISMATCH'}}});continue;}
        if(i.kind==='BANK'){const order=await tx.paymentOrder.findUniqueOrThrow({where:{id:p.orderId}});await financialLock(tx,order.sanatoriumId);const fee=BigInt(row.fee);if(!row.bank_reference||row.state!==2||fee>=p.amount)fail('BANK_ROW_INVALID','Bank satrining summa va referenceini tekshiring',422);const source=`bank:${row.bank_reference}:${p.id}`;const existing=await tx.ledgerJournal.findUnique({where:{source}});if(existing){const line=await tx.ledgerLine.findFirst({where:{journalId:existing.id,account:'BANK'}});if(line?.debit!==p.amount-fee)fail('IDEMPOTENCY_CONFLICT','Bank reference boshqa summa bilan ishlatilgan');}else await post(tx,source,'Provayderdan bankka hisob-kitob',[{account:'BANK',debit:p.amount-fee},...(fee>0n?[{account:'PROCESSING_EXPENSE',debit:fee}]:[]),{account:'PSP_CLEARING',credit:p.amount}],order.sanatoriumId,order.bookingId??undefined);}
      }await audit(tx,actor.id,'reconciliation.imported',record.id);return record;});
  }
  async differences(actor:Actor){requirePlatform(actor,'reconciliation.manage');return this.db.reconciliationDifference.findMany({take:200});}
}
